FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt upgrade -y && \
    apt install -y python3 python3-pip python3-yaml ca-certificates && \
    apt clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app/

COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt
