services:
  homenasbot-base:
    image: homenasbot-base:latest
    build:
      context: .
      dockerfile: Dockerfile.base
      network: host
    profiles:
      - build

  homenasbot:
    image: homenasbot:latest
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    volumes:
      - ./xtmp-cnf.yaml:/app/xtmp-cnf.yaml:ro
      - ./xtmp-docker:/xtmp-docker
      - type: bind
        source: /
        target: /host
        read_only: true
        bind:
          propagation: rslave
      - /var/run/docker.sock:/var/run/docker.sock:ro
    extra_hosts:
      - "nas.home:192.168.88.25"
    environment:
      CONFIG_PATH: /app/xtmp-cnf.yaml
    restart: unless-stopped
